<?php

declare(strict_types=1);

/**
 * Public-surface contract guard for the PHP SDK.
 *
 * This file is checked by ``vendor/bin/phpstan analyse`` at level: max
 * via ``composer lint``. It exists purely as a guard: each typed
 * property, return-type annotation, and ``class_exists`` /
 * ``method_exists`` probe asserts that a specific public symbol
 * exists with the locked signature. PHPStan fails the moment a
 * guarded export is renamed, removed, or has its signature drifted.
 *
 * This complements two pre-existing layers of drift detection:
 *
 *   1. packages/php/PUBLIC_API.txt — snapshot of every public symbol.
 *      Captures ANY shape change; regenerated by
 *      ``scripts/sdk-public-api.sh regenerate`` and diff-gated by CI
 *      (.github/workflows/sdk-public-api.yml). The primary surface
 *      guard.
 *   2. The mirrored TypeScript contract at
 *      packages/ts/src/__contract__.ts (PR #366), which originally
 *      introduced this pattern.
 *
 * This file is the strongest tier: it makes the contract a lint
 * dependency. A rename never reaches main without Contract.php
 * re-pointing or PHPStan failing under composer lint.
 */

namespace Isa\Sdk\Internal;

use Isa\Sdk\Account\AccountClient;
use Isa\Sdk\Isa;
use Isa\Sdk\Proxy\ProxyClient;
use Isa\Sdk\RapidSign\RapidSignClient;
use Isa\Sdk\Zyins\Cases\CaseRecord;
use Isa\Sdk\Zyins\Cases\CaseStorage;
use Isa\Sdk\Zyins\Cases\CaseStoragePutResult;
use Isa\Sdk\Zyins\Cases\ZeroKnowledgeCaseStorage;
use Isa\Sdk\Zyins\Exception\IsaAuthException;
use Isa\Sdk\Zyins\Exception\IsaConfigException;
use Isa\Sdk\Zyins\Exception\IsaException;
use Isa\Sdk\Zyins\Exception\IsaIdempotencyConflictException;
use Isa\Sdk\Zyins\Exception\IsaLicenseException;
use Isa\Sdk\Zyins\Exception\IsaRateLimitException;
use Isa\Sdk\Zyins\Exception\IsaUnsupportedException;
use Isa\Sdk\Zyins\Exception\IsaValidationException;
use Isa\Sdk\Zyins\Options\BundledApiVersions;
use Isa\Sdk\Zyins\Reference\AutocompleteAlgorithmInterface;
use Isa\Sdk\Zyins\Reference\AutocompleteOptions;
use Isa\Sdk\Zyins\Reference\AutocorrectorFactory;
use Isa\Sdk\Zyins\Reference\AutocorrectorInterface;
use Isa\Sdk\Zyins\Reference\ConditionRow;
use Isa\Sdk\Zyins\Reference\DefaultAutocompleteAlgorithm;
use Isa\Sdk\Zyins\Reference\DefaultAutocorrector;
use Isa\Sdk\Zyins\Reference\DefaultMatchAlgorithm;
use Isa\Sdk\Zyins\Reference\MatchAlgorithmInterface;
use Isa\Sdk\Zyins\Reference\MedicationRow;
use Isa\Sdk\Zyins\Reference\NicotineOptionRow;
use Isa\Sdk\Zyins\Reference\Relation;
use Isa\Sdk\Zyins\Reference\Sort;
use Isa\Sdk\Zyins\Reference\SpellingCorrectionRow;
use Isa\Sdk\Zyins\Reference\Suggestion;
use Isa\Sdk\Zyins\Reference\SuggestionBucket;
use Isa\Sdk\Zyins\ZyInsClient;

/**
 * Compile-time pins for the public surface. Static-only; the class is
 * never instantiated. Each typed property and method-return reference
 * fails PHPStan if the canonical name or signature drifts.
 *
 * @internal Contract guard — not part of the consumer API surface.
 *
 * @phpstan-ignore-next-line class.unused — intentional: contract probes only.
 */
final class Contract
{
    /* =====================================================================
     * Tier 1 — Top-level Isa constructor + namespace factories.
     * =====================================================================
     *
     * A rename, signature drift, or removal of any of these fails
     * PHPStan immediately. The factories are the entry points every
     * integrator uses on first reference.
     */

    /**
     * Pin the four canonical factories. Each returns the Isa class.
     * A rename here (e.g. ``withBearer`` → ``withToken``) makes the
     * static-call expression unresolvable.
     */
    public static function pinFactories(): Isa
    {
        // Reference each factory's existence by name via static
        // analysis — PHPStan resolves the static-call expression at
        // lint time. A rename breaks the reference.
        $_a = [Isa::class, 'withBearer'];
        $_b = [Isa::class, 'withKeycode'];
        $_c = [Isa::class, 'forForm'];
        $_d = [Isa::class, 'authenticate'];
        $_e = [Isa::class, 'fromEnv'];
        // Return one so PHPStan sees the return type lock.
        return Isa::fromEnv();
    }

    /**
     * Pin the namespace accessor properties on Isa. Renaming any of
     * these breaks the property-fetch expression.
     */
    public static function pinNamespaces(Isa $isa): ZyInsClient
    {
        $_zyins = $isa->zyins;
        $_account = $isa->account;
        $_proxy = $isa->proxy;
        $_rapidsign = $isa->rapidsign;
        return $isa->zyins;
    }

    /* =====================================================================
     * Tier 1 — Per-surface API-version map.
     * =====================================================================
     *
     * BundledApiVersions::MAP is the locked-spec per-surface pin map.
     * A constant rename breaks the reference; a resolve() rename breaks
     * the call.
     */

    /**
     * @return array<string, string>
     */
    public static function pinBundledApiVersions(): array
    {
        $_map = BundledApiVersions::MAP;
        $_resolved = BundledApiVersions::resolve('prequalify');
        return BundledApiVersions::MAP;
    }

    /* =====================================================================
     * Tier 1 — CaseStorage contract.
     * =====================================================================
     *
     * Every adapter implementing the put / get round-trip MUST
     * implement CaseStorage; the default ZeroKnowledgeCaseStorage
     * exists at the documented path. CaseRecord / CaseStoragePutResult
     * are the wire value types.
     */

    public static function pinCaseStorage(CaseStorage $storage, CaseRecord $record): ?CaseRecord
    {
        $_put = $storage->put($record);
        $_get = $storage->get('case_id');
        return $_get;
    }

    /**
     * Default zero-knowledge adapter exists and remains constructible
     * by class name.
     *
     * @return class-string<ZeroKnowledgeCaseStorage>
     */
    public static function pinZeroKnowledgeCaseStorage(): string
    {
        return ZeroKnowledgeCaseStorage::class;
    }

    /**
     * PutResult shape — the canonical adapter return type.
     */
    public static function pinPutResult(CaseStoragePutResult $r): string
    {
        return $r->id;
    }

    /* =====================================================================
     * Tier 1 — Reference matcher surface.
     * =====================================================================
     *
     * Per locked-spec docs/sdk-syntax-proposal.md §reference: the
     * Sort enum members (MOST_COMMON_FIRST / ALPHABETICAL) are the
     * documented sort vocabulary on matcher results.
     */

    public static function pinSort(): string
    {
        $_a = Sort::MOST_COMMON_FIRST;
        $_b = Sort::ALPHABETICAL;
        return Sort::MOST_COMMON_FIRST;
    }

    /* =====================================================================
     * Tier 1 — Reference adapters (rc.1 → 1.0 cutover).
     * =====================================================================
     *
     * Three adapter interfaces (Autocorrector, MatchAlgorithm,
     * AutocompleteAlgorithm) + their default implementations. The
     * autocorrector kernel factory `Isa::autocorrector()` returns
     * {@see AutocorrectorFactory}. Suggestion + SuggestionBucket pin the
     * autocomplete result shape. Inline-row value types
     * (ConditionRow / MedicationRow / NicotineOptionRow /
     * SpellingCorrectionRow / Relation) replace the legacy maps-shape.
     */

    /**
     * @return list<class-string>
     */
    public static function pinReferenceAdapters(): array
    {
        $_a = AutocorrectorInterface::MODE_KEYUP;
        $_b = AutocorrectorInterface::MODE_SUBMIT;
        /** @var list<class-string> $out */
        $out = [
            AutocorrectorInterface::class,
            DefaultAutocorrector::class,
            MatchAlgorithmInterface::class,
            DefaultMatchAlgorithm::class,
            AutocompleteAlgorithmInterface::class,
            DefaultAutocompleteAlgorithm::class,
            AutocompleteOptions::class,
            Suggestion::class,
            AutocorrectorFactory::class,
        ];
        return $out;
    }

    public static function pinSuggestionBucket(): string
    {
        $_a = SuggestionBucket::STARTS_WITH;
        $_b = SuggestionBucket::SAME_WORDS;
        $_c = SuggestionBucket::INDEPENDENT_WORD_INTERSECTION;
        $_d = SuggestionBucket::WORD_COUNT_NO_TOLERANCE;
        $_e = SuggestionBucket::SAME_NUM_WITH_TOLERANCE;
        $_f = SuggestionBucket::WORD_COUNT_WITH_TOLERANCE;
        return SuggestionBucket::STARTS_WITH;
    }

    /**
     * @return list<class-string>
     */
    public static function pinDatasetRowTypes(): array
    {
        /** @var list<class-string> $out */
        $out = [
            ConditionRow::class,
            MedicationRow::class,
            NicotineOptionRow::class,
            SpellingCorrectionRow::class,
            Relation::class,
        ];
        return $out;
    }

    // =====================================================================
    // Tier 1 — Error hierarchy.
    // =====================================================================
    //
    // Renames break ``catch`` clauses in user code. Each documented
    // subclass MUST remain catchable under its canonical name.

    /**
     * @return list<class-string<IsaException>>
     */
    public static function pinErrors(): array
    {
        /** @var list<class-string<IsaException>> $out */
        $out = [
            IsaException::class,
            IsaAuthException::class,
            IsaConfigException::class,
            IsaIdempotencyConflictException::class,
            IsaLicenseException::class,
            IsaRateLimitException::class,
            IsaUnsupportedException::class,
            IsaValidationException::class,
        ];
        return $out;
    }

    // =====================================================================
    // Tier 1 — Namespace clients.
    // =====================================================================
    //
    // ZyInsClient / AccountClient / ProxyClient / RapidSignClient are
    // the four canonical sub-namespace types. Pinning by class-string
    // catches rename/move; a class-not-found error fails phpstan.

    /**
     * @return list<class-string>
     */
    public static function pinClients(): array
    {
        /** @var list<class-string> $out */
        $out = [
            ZyInsClient::class,
            AccountClient::class,
            ProxyClient::class,
            RapidSignClient::class,
        ];
        return $out;
    }
}
